### ISSUE TITLE
species and refs are empty lists in some of r.KMvalues.items() while it doesn't look like this in the original txt-data and in the online version of Brenda

### ISSUE THREAD

**Issue by PolinaShichkova** [Robaina/BRENDApyrser#2]
Hello,

Sorry to bother you again. I'm not sure, but probably I noticed something unexpected again. Here is an example:

`brenda = BRENDA(brenda_txt_file)

for r in brenda.reactions: 
    if r.ec_number == "1.14.18.9":
        for met,vals in r.KMvalues.items():
            print("EC:",r.ec_number, "metab:", met, "data:",str(vals))`

The output of which has empty lists in species and refs:
EC: 1.14.18.9 metab: 4alpha-methyl-5alpha-cholestan-3beta-ol data: [{'value': 0.125, 'species': [], 'meta': '#2# at pH 7.4 and37Â°C <11>', 'refs': []}]

However, when I go to both Brenda-txt and online version of Brenda, I see that this Km value is from Rattus norvegicus.
I didn't go into the details of your code, but probably empty species output is due to slightly different line pattern for this case (as well as some other cases): "PR      #2# Rattus norvegicus   (#2# isoform RBCK1 <1>) <1,2,11,12,13>"  [most lines of PR don't have a part with "(...)"]. Sorry if it's due to any intentional aspect to omit these data in your parser.

Thank you!

Best regards,
Polina

**Comment by PolinaShichkova** [comment]
Thank you! Sorry for bothering you

**Comment by Robaina** [comment]
No problem, thank you for finding out these bugs! sorry for the very late reply. I fixed the issue of parsing species in the new version of the code. Closing this issue for now, feel free to reopen or open a different issue.
