### ISSUE TITLE
Encoding problem with reading files downloaded from brenda

### ISSUE THREAD

**Issue by MistyField** [Robaina/BRENDApyrser#7]
The .txt file downloaded from http:/www.brenda-enzymes.org is encoded in utf-8. But in the line 76 of parser.py it's:
`with open(path_to_database, encoding="iso-8859-1") as file:`
maybe it should be changed into:
`with open(path_to_database, encoding="utf-8") as file:`?
because if the file was decoded in iso-8859-1, the meta of the reaction may become
`'#4# pH 7.0, 30Â°C, recombinantwild-type enzyme <6>; #4# pH 7.0, 30Â°C, recombinant free enzyme <8>'`
but if it was changed into utf-8, it turns normal: `'#4# pH 7.0, 30°C, recombinantwild-type enzyme <6>; #4# pH 7.0, 30°C, recombinant free enzyme <8>'`

**Comment by Robaina** [comment]
Hi @MistyField ,

thanks for noticing this and apologies for the late reply. I don't remember now why I used that particular encoding but you are right there. I'm planning to update BRENDApyrser to accommodate the "new" json format BRENDA released a while ago, see issue #9. It doesn't make much sense to continue parsing the txt file having now a json.

Best!

**Comment by Robaina** [comment]
Issue solved in PR #8
